export enum ActionTypes {
  SELECTED_PAYMENT_METHOD = 'SELECTED_PAYMENT_METHOD',
  GET_AVAILABLE_PAYMENT_METHODS = 'GET_AVAILABLE_PAYMENT_METHODS',
  SET_AVAILABLE_PAYMENT_METHODS = 'SET_AVAILABLE_PAYMENT_METHODS',
}
