export enum ActionTypes {
  LOG_OUT = 'LOG_OUT',
  GET_USER_INFO = 'GET_USER_INFO',
  SET_USER_INFO = 'SET_USER_INFO',
  IS_AUTHORIZED = 'IS_AUTHORIZED',
  VK_OAUTH_TOKEN = 'VK_OAUTH_TOKEN',
  SET_USER_TOKEN_TO_LOCAL_STORAGE = 'SET_USER_TOKEN_TO_LOCAL_STORAGE',
}
