export const enum ActionTypes {
  SET_ANNOUNCE = 'SET_ANNOUNCE',
  GET_CAR_MESSAGE = 'GET_CAR_MESSAGE',
  SET_CAR_MESSAGE = 'SET_CAR_MESSAGE',
  ADD_CAR_NEW_BET = 'ADD_CAR_NEW_BET',
  START_NEW_SESSION = 'START_NEW_SESSION',
  SET_CAR_WS_CHANNEL = 'SET_CAR_WS_CHANNEL',
  GET_HISTORY_MESSAGE = 'GET_HISTORY_MESSAGE',
  CLOSE_CAR_WS_CHANNEL = 'CLOSE_CAR_WS_CHANNEL',
  CREATE_CAR_WS_CHANNEL = 'CREATE_CAR_WS_CHANNEL',
}
