export const enum ActionTypes {
  SET_WS = 'SET_WS',
  SEND_MESSAGE = 'SEND_MESSAGE',
  GET_ONLINE_MESSAGE = 'GET_ONLINE_MESSAGE',
  SET_ONLINE_MESSAGE = 'SET_ONLINE_MESSAGE',
  GET_MAIN_CHAT_MESSAGE = 'GET_MAIN_CHAT_MESSAGE',
  SET_MAIN_CHAT_MESSAGE = 'SET_MAIN_CHAT_MESSAGE',
  CLOSE_MAIN_CHAT_WS_CHANNEL = 'CLOSE_MAIN_CHAT_WS_CHANNEL',
  CREATE_MAIN_CHAT_WS_CHANNEL = 'CREATE_MAIN_CHAT_WS_CHANNEL',
}
